# Generated by Django 4.2.3 on 2023-08-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=50)),
                ('time', models.TimeField(default='00:00')),
                ('date', models.DateField()),
                ('towhom', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=300)),
            ],
        ),
    ]
