# Generated by Django 4.2.3 on 2023-09-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=50)),
                ('time', models.TimeField(default='00:00')),
                ('date', models.DateField()),
                ('towhom', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=300)),
                ('markasdone', models.BooleanField(default=False)),
                ('private', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(max_length=50)),
                ('isShopped', models.BooleanField(default=0)),
            ],
        ),
    ]
