# Generated by Django 4.2.3 on 2023-09-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='towhom_email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
