# Generated by Django 4.2.3 on 2023-09-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_addtask_towhom_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='dateTime',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
    ]
