# Generated by Django 4.2.3 on 2023-08-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_addtask_markasdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
