# Generated by Django 4.2.3 on 2023-08-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_addtask_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='private',
            field=models.BooleanField(),
        ),
    ]
