# Generated by Django 4.2.3 on 2023-08-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_addtask_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(max_length=50)),
                ('isShopped', models.BooleanField(default=0)),
            ],
        ),
    ]
