# Generated by Django 4.2.3 on 2023-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_shoppingproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingproducts',
            name='iwilldo',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
