# Generated by Django 4.2.3 on 2023-09-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_shoppingproducts_iwilldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingproducts',
            name='iwilldo',
        ),
    ]
